In [52]:
import pandas as pd

In [53]:
df = pd.DataFrame(data = pd.read_csv("training.csv"))

In [54]:
df

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,gas,std,four,sedan,rwd,front,104.3,188.8,67.2,56.2,...,141.0,mpfi,NaN,3.15,9.5,114.0,5400.0,24.0,28.0,15985.0
1,gas,std,four,wagon,fwd,front,94.5,170.2,63.8,53.5,...,97.0,2bbl,3.15,3.29,9.4,69.0,5200.0,31.0,37.0,7349.0
2,gas,std,four,sedan,fwd,front,94.5,165.3,63.8,54.5,...,NaN,2bbl,3.15,3.29,9.4,69.0,5200.0,31.0,37.0,6849.0
3,gas,std,four,sedan,rwd,front,104.5,187.8,66.5,54.1,...,171.0,mpfi,3.27,3.35,9.2,156.0,5200.0,20.0,24.0,15690.0
4,gas,std,four,sedan,fwd,front,93.7,167.3,NaN,50.8,...,90.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6692.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,diesel,turbo,four,wagon,rwd,front,110.0,190.9,70.3,58.7,...,183.0,idi,3.58,3.64,21.5,123.0,4350.0,22.0,25.0,28248.0
160,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,...,156.0,spdi,3.59,3.86,7.0,145.0,5000.0,19.0,24.0,14489.0
161,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,50.6,...,90.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,7609.0
162,gas,std,two,hatchback,fwd,front,93.7,156.9,63.4,53.7,...,97.0,2bbl,3.62,2.36,NaN,69.0,4900.0,31.0,36.0,5118.0
163,gas,std,four,wagon,4wd,front,95.7,169.7,63.6,NaN,...,92.0,2bbl,3.05,3.03,9.0,62.0,4800.0,27.0,32.0,8778.0

In [55]:
train_x = df.iloc[:,:-1]

In [56]:
train_y  = df["price"]

In [57]:
train_y.describe()

count      155.000000
mean     12915.859142
std       7732.218402
min       5118.000000
25%       7744.000000
50%      10198.000000
75%      15991.500000
max      45400.000000
Name: price, dtype: float64

In [58]:
df.dropna(subset=["price"])

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,gas,std,four,sedan,rwd,front,104.3,188.8,67.2,56.2,...,141.0,mpfi,NaN,3.15,9.5,114.0,5400.0,24.0,28.0,15985.0
1,gas,std,four,wagon,fwd,front,94.5,170.2,63.8,53.5,...,97.0,2bbl,3.15,3.29,9.4,69.0,5200.0,31.0,37.0,7349.0
2,gas,std,four,sedan,fwd,front,94.5,165.3,63.8,54.5,...,NaN,2bbl,3.15,3.29,9.4,69.0,5200.0,31.0,37.0,6849.0
3,gas,std,four,sedan,rwd,front,104.5,187.8,66.5,54.1,...,171.0,mpfi,3.27,3.35,9.2,156.0,5200.0,20.0,24.0,15690.0
4,gas,std,four,sedan,fwd,front,93.7,167.3,NaN,50.8,...,90.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6692.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,diesel,turbo,four,wagon,rwd,front,110.0,190.9,70.3,58.7,...,183.0,idi,3.58,3.64,21.5,123.0,4350.0,22.0,25.0,28248.0
160,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,...,156.0,spdi,3.59,3.86,7.0,145.0,5000.0,19.0,24.0,14489.0
161,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,50.6,...,90.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,7609.0
162,gas,std,two,hatchback,fwd,front,93.7,156.9,63.4,53.7,...,97.0,2bbl,3.62,2.36,NaN,69.0,4900.0,31.0,36.0,5118.0
163,gas,std,four,wagon,4wd,front,95.7,169.7,63.6,NaN,...,92.0,2bbl,3.05,3.03,9.0,62.0,4800.0,27.0,32.0,8778.0

In [69]:
cat = train_x.select_dtypes(["object"]).columns.tolist()

In [60]:
from sklearn.preprocessing import OneHotEncoder

In [61]:
encoder = OneHotEncoder()

In [63]:
b = encoder.fit_transform(train_x[cat]).toarray()

In [49]:
encoder.get_feature_names

<bound method OneHotEncoder.get_feature_names of OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)>

In [50]:
a = pd.DataFrame(b,columns = encoder.get_feature_names())

In [76]:
c = pd.DataFrame(train_x[train_x.select_dtypes(["float64"]).columns.tolist()],columns = train_x.select_dtypes(["float64"]).columns.tolist())

In [77]:
a.join(c)

,x0_diesel,x0_gas,x1_std,x1_turbo,x2_four,x2_two,x3_convertible,x3_hardtop,x3_hatchback,x3_sedan,...,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,56.2,NaN,141.0,NaN,3.15,9.5,114.0,5400.0,24.0,28.0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,53.5,2024.0,97.0,3.15,3.29,9.4,69.0,5200.0,31.0,37.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,54.5,1938.0,NaN,3.15,3.29,9.4,69.0,5200.0,31.0,37.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,54.1,NaN,171.0,3.27,3.35,9.2,156.0,5200.0,20.0,24.0
4,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,50.8,1989.0,90.0,2.97,3.23,9.4,68.0,5500.0,31.0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,58.7,3750.0,183.0,3.58,3.64,21.5,123.0,4350.0,22.0,25.0
160,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,50.2,2926.0,156.0,3.59,3.86,7.0,145.0,5000.0,19.0,24.0
161,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,50.6,NaN,90.0,2.97,3.23,9.4,68.0,5500.0,31.0,38.0
162,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,53.7,2050.0,97.0,3.62,2.36,NaN,69.0,4900.0,31.0,36.0
163,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,3110.0,92.0,3.05,3.03,9.0,62.0,4800.0,27.0,32.0